import 'dart:convert';

import 'package:html/parser.dart' as html_parser;

import '../models/academic_progress.dart';
import '../models/common.dart';

class AcademicProgressIndex {
  const AcademicProgressIndex({
    required this.studentId,
    required this.gpa,
    required this.plannedCourses,
    required this.passedCourses,
    required this.ongoingCourses,
    required this.notTakenCourses,
    required this.formValues,
    required this.nodes,
  });

  final String studentId;
  final String gpa;
  final int? plannedCourses;
  final int? passedCourses;
  final int? ongoingCourses;
  final int? notTakenCourses;
  final Map<String, String> formValues;
  final List<AcademicProgressNode> nodes;
}

class AcademicProgressParser {
  const AcademicProgressParser._();

  static String parseStudentId(String source) =>
      html_parser
          .parse(source)
          .querySelector('form#form input[name="xh_id"]')
          ?.attributes['value']
          ?.trim() ??
      '';

  // The school's index response contains JavaScript that builds the tree. Its
  // <ul class="treeview"> is empty until that script runs in a browser.
  static final _nodePattern = RegExp(
    r"<li id='li([^']+)'[^\n]*?fxfyqjd_id='([^']*)'",
  );
  static final _literalPattern = RegExp(r'"([^"<>+]{1,100})"');

  static AcademicProgressIndex parseIndex(String source) {
    final document = html_parser.parse(source);
    final formValues = <String, String>{};
    for (final input in document.querySelectorAll('form#form input[name]')) {
      final name = input.attributes['name'];
      if (name != null) formValues[name] = input.attributes['value'] ?? '';
    }
    final summary = document.querySelector('#alertBox')?.text ?? '';
    final nodes = <AcademicProgressNode>[];
    final seen = <String>{};

    for (final match in _nodePattern.allMatches(source)) {
      final id = match.group(1)!;
      if (seen.contains(id) || id == 'zgzsxx' || id == 'cxcyqkxfyq') {
        continue;
      }
      final end = (match.end + 1500).clamp(0, source.length);
      final fragment = source.substring(match.end, end);
      final escapedId = RegExp.escape(id);
      final title = RegExp(
        "xfyqjd_id='$escapedId' jdkcsx='([^']*)' leaf='([^']*)' sfmjd='([^']*)'",
      ).firstMatch(fragment);
      final credits = RegExp(
        "id='p$escapedId' yxxf='([^']*)' yqzdxf='([^']*)' sftg='([^']*)'>",
      ).firstMatch(fragment);
      if (title == null || credits == null) continue;
      final nameSource = fragment.substring(
        credits.end,
        (credits.end + 180).clamp(0, fragment.length),
      );
      String? name;
      for (final literal in _literalPattern.allMatches(nameSource)) {
        final value = html_parser
            .parseFragment(literal.group(1)!)
            .text!
            .replaceAll('\u00a0', ' ')
            .trim();
        if (value.isNotEmpty && !value.contains(':') && !value.contains(r'$')) {
          name = value;
          break;
        }
      }
      if (name == null || name.isEmpty) continue;
      seen.add(id);
      nodes.add(AcademicProgressNode(
        id: id,
        parentId: match.group(2) ?? '',
        name: name,
        requiredCredits: double.tryParse(credits.group(2) ?? ''),
        earnedCredits: double.tryParse(credits.group(1) ?? ''),
        passed: switch (credits.group(3)) {
          '1' => true,
          '0' => false,
          _ => null,
        },
        courseKind: title.group(1) ?? '',
        isLeaf: title.group(3) == '1',
      ));
    }
    // This root is generated by a separate branch of the school's inline
    // script and does not always have the credit attributes used above.
    if (source.contains('zgzsxx') && source.contains('资格证书信息')) {
      final certificateNode = const AcademicProgressNode(
        id: 'zgzsxx',
        parentId: '',
        name: '资格证书信息',
        requiredCredits: null,
        earnedCredits: null,
        passed: null,
        courseKind: 'certificate',
        isLeaf: true,
      );
      final otherCoursesIndex =
          nodes.indexWhere((node) => node.id == 'qtkcxfyq');
      nodes.insert(
        otherCoursesIndex < 0 ? nodes.length : otherCoursesIndex,
        certificateNode,
      );
    }
    if (nodes.isEmpty) {
      throw const FormatException('教务系统未返回可识别的学业结构');
    }
    return AcademicProgressIndex(
      studentId: formValues['xh_id'] ?? '',
      gpa: _first(summary, r'GPA[）)\s]*[：:]?\s*(\d+(?:\.\d+)?)') ?? '',
      plannedCourses: _number(summary, r'计划总课程\s*(\d+)'),
      passedCourses: _number(summary, r'通过\s*(\d+)'),
      ongoingCourses: _number(summary, r'在读\s*(\d+)'),
      notTakenCourses: _number(summary, r'未修\s*(\d+)'),
      formValues: formValues,
      nodes: nodes,
    );
  }

  static List<AcademicProgressCourse> parseCourses(String source) {
    final decoded = jsonDecode(source);
    if (decoded is! List) {
      throw const FormatException('教务系统返回了无法识别的学业课程数据');
    }
    return decoded.whereType<JsonMap>().map((row) {
      return AcademicProgressCourse(
        id: stringValue(row['KCH_ID']),
        code: stringValue(row['KCH']),
        name: stringValue(row['KCMC']),
        status: stringValue(row['XDZT']),
        credits: stringValue(row['XF'], stringValue(row['JHXF'])),
        grade: stringValue(row['CJ'], stringValue(row['MAXCJ'])),
        gradePoint: stringValue(row['JD']),
        academicYear: stringValue(row['CJXNMC'], stringValue(row['XNMC'])),
        term: stringValue(row['CJXQMC'], stringValue(row['XQMMC'])),
        suggestedYear: stringValue(row['JYXDXNMC']),
        suggestedTerm: stringValue(row['JYXDXQMC']),
        nature: stringValue(row['KCXZMC']),
        category: stringValue(row['KCLBMC']),
        hours: stringValue(row['XSXXXX']),
      );
    }).toList();
  }

  static List<AcademicCertificate> parseCertificates(String source) {
    final decoded = jsonDecode(source);
    if (decoded is! List) {
      throw const FormatException('教务系统返回了无法识别的资格证书数据');
    }
    return decoded.whereType<JsonMap>().map((row) {
      return AcademicCertificate(
        name: stringValue(row['XMMC']),
        acquisitionStatus: stringValue(row['SFHD']),
      );
    }).toList();
  }

  static String? _first(String source, String pattern) =>
      RegExp(pattern).firstMatch(source)?.group(1);

  static int? _number(String source, String pattern) =>
      int.tryParse(_first(source, pattern) ?? '');
}
